---
- hosts: all
  remote_user: keerthika
  vars:
    http_port: 80

  tasks:
  - name: Ensure that Apache is installed
    apt: name=apache2 state=present

  - name: Start Apache Services
    service: name=apache2 enabled=yes state=started
    
  - name: Copy Site Files
    template: src=templates/index.j2 dest={{ doc_root }}/index.html mode=0664


  
