---
- hosts: all
  remote_user: keerthika
  vars:
    http_port: 80

  tasks:
  - name: Ensure that Apache is installed
    apt: name=apache2 state=latest

  - name: Start Apache Services
    service: name=apache2 enabled=yes state=started




  
